repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.44.0"
    hooks:
      - id: eslint
        files: \.[t]sx?$
        types: [file]
        args: [--quiet]

  - repo: local
    hooks:
      - id: typescript-typecheck
        name: TypeScript Typecheck
        language: system
        entry: npm run typecheck
        files: \.[t]sx?$
        pass_filenames: false
